version: "3.8"
services:
  mongo:
    image: mongo:4.0.28
    container_name: mongo
    volumes:
      - "./mongo/db:/data/db:rw"
      - "./mongo/backup:/backup:rw"
    restart: always

  graphxr:
    image: kineviz/graphxr_try:latest
    ports:
      - 9000:9000
    volumes:
      - "./graphxr:/data:rw"
    environment:
      - "ADMIN_EMAIL=admin@graphxr.cn"
      - "ADMIN_PASSWORD=tuke"
      - "MONGO_URL=mongodb://mongo/graphxr"
    depends_on:
      - mongo
    restart: always

  neo4j:
    image: neo4j:4.4
    ports:
      - 7687:7687
      - 7474:7474
    volumes: 
      - "./neo4j/data:/data:rw"
      - "./neo4j/plugins:/plugins:rw"
      - "./neo4j/logs:/logs:rw"
      - "./neo4j/import:/var/lib/neo4j/import"
    environment:
      - "NEO4J_AUTH=neo4j/tuke"
      - "NEO4J_dbms_memory_heap_max__size=2G" 
      - "NEO4J_dbms_memory_heap_initial__size=1G" 
      - "NEO4J_dbms_memory_pagecache_size=1GB" 
      - "NEO4j_dbms_memory_transaction_global_max_size=2G"
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"
      - "NEO4J_dbms_logs_debug_rotation_size=1m"
      - "NEO4J_dbms_logs_security_rotation_size=1m"
      - "NEO4J_dbms_logs_query_rotation_size=2m"
    restart: always